version: "4"
services:
  # Servicio de la API REST
  rest-node:
    build:
      context: .
    depends_on: #Definimos que se inicie después
      - mariadb_service #Del servicio de la BD
      - phpMyAdmin
    container_name: express-api #Le asignamos un nombre
    ports: #Le asignamos un puerto
      - ${PORT}:8000 #Que será leído en las variables de entorno
    restart: always #Si se cae, se reinicia

  # Servicio mariadb
  mariadb_service:
    container_name: mariadb_database
    image: mariadb:jammy
    ports:
      - ${PORTDB}:3306
    volumes:
      - ./mariaDB:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${NAMEDB}

  # Servicio phpMyAdmin
  phpMyAdmin:
    depends_on:
      - mariadb_service
    image: phpmyadmin:5.2.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=1
